from .separators import center_text


game_element_length = 20

# Kept all the functions without applying the DRY principle for beter visualisation and edits

""" All stages of hangman drawn in CMD below"""
def zero(separator_length):
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)

def one(separator_length):
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="#"*game_element_length, length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)

def two(separator_length):
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #####" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text="#"*game_element_length, length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)

def three(separator_length):
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  " + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  " + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  " + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  " + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  " + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  " + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  " + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #####" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text="#"*game_element_length, length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)

def four(separator_length):
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #################"), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  #" + " "*(game_element_length-7)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   # #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  " + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  " + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  " + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  " + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #####" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text="#"*game_element_length, length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)

def five(separator_length):
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #################"), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  #         #   "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   # #         ###  "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #           ###  "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  " + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  " + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  " + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #####" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text="#"*game_element_length, length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)

def six(separator_length):
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #################"), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  #         #   "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   # #         ###  "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #           ###  "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #          ##### "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #          #   # "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #          #   # "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #####        ##### "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text="#"*game_element_length, length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)

def seven(separator_length):
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #################"), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  #         #   "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   # #         ###  "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #           ###  "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #          ##### "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #         ##   # "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #         ##   # "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #####        ##### "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text="#"*game_element_length, length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)

def eight(separator_length):
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #################"), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  #         #   "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   # #         ###  "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #           ###  "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #          ##### "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #         ##   ##"), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #         ##   ##"), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #####        ##### "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #" + " "*(game_element_length-6)), length=separator_length, draw_border=True, double_border=True)
    center_text(text="#"*game_element_length, length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)

def nine(separator_length):
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #################"), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  #         #   "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   # #         ###  "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #           ###  "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #          ##### "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #         ##   ##"), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #         ##   ##"), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #####        ##### "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #         #    "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #        ##    "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #              "), length=separator_length, draw_border=True, double_border=True)
    center_text(text="#"*game_element_length, length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)

def ten(separator_length):
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #################"), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #  #         #   "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   # #         ###  "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #           ###  "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #          ##### "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #         ##   ##"), length=separator_length, draw_border=True, double_border=True)
    center_text(text=("   #         ##   ##"), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #####        ##### "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #         # #  "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #        ## ## "), length=separator_length, draw_border=True, double_border=True)
    center_text(text=(" #   #              "), length=separator_length, draw_border=True, double_border=True)
    center_text(text="#"*game_element_length, length=separator_length, draw_border=True, double_border=True)
    center_text(text="", length=separator_length, draw_border=True, double_border=True)
